### ISSUE TITLE
[BUG] lifecycle tests crash

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#463] opened 2023-04-21 06:34 UTC
The Lifecycle integration tests crash for me on their own due to programming errors.

```
│ ~/repos/suse/ceph/qa/rgw/store/sfs/tests │ 1 ► python3 -m unittest test-sfs-lifecycle-smoke.py 
EEE
======================================================================
ERROR: test_expiration (test-sfs-lifecycle-smoke.LifecycleSmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moritz/repos/suse/ceph/qa/rgw/store/sfs/tests/test-sfs-lifecycle-smoke.py", line 53, in tearDown
    self.s3_client.close()
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 645, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'S3' object has no attribute 'close'

======================================================================
ERROR: test_expiration_multiple_buckets (test-sfs-lifecycle-smoke.LifecycleSmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moritz/repos/suse/ceph/qa/rgw/store/sfs/tests/test-sfs-lifecycle-smoke.py", line 53, in tearDown
    self.s3_client.close()
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 645, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'S3' object has no attribute 'close'

======================================================================
ERROR: test_lifecycle_versioning_enabled (test-sfs-lifecycle-smoke.LifecycleSmokeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/moritz/repos/suse/ceph/qa/rgw/store/sfs/tests/test-sfs-lifecycle-smoke.py", line 53, in tearDown
    self.s3_client.close()
  File "/usr/lib/python3.6/site-packages/botocore/client.py", line 645, in __getattr__
    self.__class__.__name__, item)
AttributeError: 'S3' object has no attribute 'close'

----------------------------------------------------------------------
Ran 3 tests in 136.661s

FAILED (errors=3)

```

**Comment by 0xavi0** [comment] 2023-04-21 08:25
As discussed in Slack: something is wrong in our CI infrastructure.

Lifecycle tests depend on the lifecycle debug period time (10 seconds).
It simulates 1 day with that debug period.

Those test are more affected by the CI issue, because tests are executing super slow.

This [job](https://github.com/aquarist-labs/ceph/actions/runs/4753028336/jobs/8444119828) job has the LC tests disabled and took 36 minutes to run the integration tests.

This [job](https://github.com/aquarist-labs/ceph/actions/runs/4762299260/jobs/8464381061?pr=144) took 2m 45s, and it included the LC tests.
The only difference between both is that the first one was executed in our CI infra and the second in GH's.

Even I disabled the life cycle tests in the [job](https://github.com/aquarist-labs/ceph/actions/runs/4753028336/jobs/8445596628), another s3test failed... 
```bash
+ jq '.tests[] | select( .result == "failure" ) | .name' /runner/_work/ceph/ceph/s3test-results/report.json
"test_atomic_read_4mb"
+ _has_failed_tests
++ jq '.tests[] | select( .result == "failure" ) | .name' /runner/_work/ceph/ceph/s3test-results/report.json
+ '[' -z '"test_atomic_read_4mb"' ']'
Error: Process completed with exit code 1.
```

It's the first time I see that particular test failing. And the execution of all s3 tests took 1:30h....

**Comment by 0xavi0** [comment] 2023-04-24 13:50
I'm closing this as the issue is gone once CI has decent executions times again.

**Closed as completed by 0xavi0** 2023-04-24 13:50 UTC
Labels: kind/bug, area/tests
