### ISSUE TITLE
S3 Test test_multipart_copy_special_names fails in cleanup bucket phase with Bucket Not Empty

### ISSUE THREAD

**Issue by irq0** [s3gw-tech/s3gw#699] opened 2023-09-01 15:31 UTC
The test itself succeeds, but something is not properly cleaned up so that teardown() fails

**Comment by jhmarina** [comment] 2023-09-07 10:41
Duplicate of https://github.com/aquarist-labs/s3gw/issues/517

**Closed as not planned by jhmarina** 2023-09-07 10:41 UTC
Labels: kind/bug, area/rgw-sfs
