### ISSUE TITLE
chart: extend chart to rancher app

### ISSUE THREAD

**Issue by m-ildefons** [s3gw-tech/s3gw#60] opened 2022-08-11 12:19 UTC
Extend chart to rancher app[1], so that seamless integration with rancher is possible

[1]: https://rancher.com/docs/rancher/v2.6/en/helm-charts/creating-apps/

**Comment by jhmarina** [comment] 2022-09-28 11:30
This is a duplicate of this https://github.com/orgs/aquarist-labs/projects/5/views/12

**Closed as completed by jhmarina** 2022-09-28 11:30 UTC
Labels: triage/duplicate
