### ISSUE TITLE
Lifecycle rules support on UI (editor/validator)

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#269] opened 2022-12-13 14:28 UTC
### What needs to be done

This is a placeholder. Information tba.

**Comment by votdev** [comment] 2023-03-02 10:07
Is this a duplicate of [#349](https://github.com/aquarist-labs/s3gw/issues/349)?

**Comment by jhmarina** [comment] 2023-03-07 09:40
yes, I think it is. Closing it now

**Closed as completed** 2023-05-24 12:20 UTC
Labels: triage/duplicate, area/ui, kind/feature
