### ISSUE TITLE
UI: upload, download, manage buckets/objects/files

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#46] opened 2022-07-18 14:28 UTC

**Comment by votdev** [comment] 2022-09-12 10:47
Is this issue a duplicate of https://github.com/aquarist-labs/s3gw/issues/44?

**Comment by votdev** [comment] 2022-09-12 10:48
@jhmarina Is this issue a duplicate of https://github.com/aquarist-labs/s3gw/issues/44?

**Comment by votdev** [comment] 2022-10-05 12:53
Duplicate

**Closed as not planned by votdev** 2022-10-05 12:53 UTC
Labels: triage/duplicate, kind/enhancement, area/ui
