### ISSUE TITLE
UI: Enable versioning in the UI

### ISSUE THREAD

**Issue by jhmarina** [s3gw-tech/s3gw#254] opened 2022-12-02 16:52 UTC
### What needs to be done

Enable versioning in the UI. We have a checkbox to enable it, but this will involve creating an interface to visualize different versions of a file and relevant data. We may need to mock the UI up before implementing.

### Why it needs to be done

Versioning is enabled in the backend and can be managed via the CLI. Having it in the UI should also be an option.

### Acceptance Criteria

The user can manage file versioning through the UI.

### Additional Information

n/a

**Comment by votdev** [comment] 2023-02-10 12:51
Duplicate of https://github.com/aquarist-labs/s3gw/issues/271.

**Comment by votdev** [comment] 2023-02-10 12:51
@jhmarina Can we close that?

**Closed as completed** 2023-02-13 08:45 UTC
Labels: triage/duplicate, kind/enhancement, area/ui
