### ISSUE TITLE
rgw/sfs: Default retention mode is not applied to new bucket objects

### ISSUE THREAD

**Issue by votdev** [s3gw-tech/s3gw#772] opened 2023-10-23 14:20 UTC
When a retention mode is set during the bucket creation, these settings are not applied to objects that are created via upload.

![Peek 2023-10-23 16-19](https://github.com/aquarist-labs/s3gw/assets/1897962/1f7d33ac-8a30-4c4e-a604-ce4b86bca442)

References:
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/upload_fileobj.html
- https://github.com/aquarist-labs/s3gw-ui/blob/main/src/backend/api/objects.py#L725

Tested with the latest nightly build of s3gw from 22.10.2023.

**Comment by giubacc** [comment] 2023-10-23 15:02
duplicate of : https://github.com/aquarist-labs/s3gw/issues/761

**Closed as not planned** 2023-10-24 14:02 UTC
Labels: kind/bug, triage/duplicate, area/rgw-sfs
